library(DBI)
library(RMySQL)
library(DT)
library(ggplot2)
library(plotly)
library(dplyr)
library(pier)
library(RColorBrewer)

con <- dbConnect(MySQL(), user = 'root', password = '', host = '127.0.0.1', dbname = 'classicmodels')
emp_list <- dbGetQuery(con, 'SELECT CONCAT(employees.firstName, " ", employees.lastName) AS employee_name FROM employees')
prod_list <- dbGetQuery(con, 'SELECT DISTINCT productLine FROM products')
office_list <- dbGetQuery(con, 'SELECT CONCAT(offices.city, ", ", offices.country) AS office FROM offices')
cust_list <- dbGetQuery(con, 'SELECT customerName FROM customers')
